-- Data export
INSERT INTO checkpoints (id, location_name, lat, lng, description, created_at) VALUES (1, 'Surabaya', -7.2575, 112.7521, 'Start dari Surabaya pagi-pagi buta. Kota masih sepi, jalanan basah habis hujan semalam. Gas pertama ke selatan.', '2026-04-11 05:30:00');
INSERT INTO checkpoints (id, location_name, lat, lng, description, created_at) VALUES (2, 'Mojokerto', -7.47, 112.4333, 'Berhenti sejenak di Mojokerto. Mampir sarapan nasi pecel pinggir jalan, sambelnya nendang banget. Dari sini mulai naik ke arah gunung.', '2026-04-11 07:15:00');
INSERT INTO checkpoints (id, location_name, lat, lng, description, created_at) VALUES (3, 'Malang', -7.9797, 112.6304, 'Malang sudah keliatan dingin dari jauh. Kabut turun dari Semeru. Istirahat dulu di sini sebelum lanjut ke barat.', '2026-04-11 10:00:00');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (1, 1, '/uploads/seed/sby-1.jpg', 'Gate keberangkatan. Motor udah siap, carrier penuh, GPS nyala.', 0, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (2, 1, '/uploads/seed/sby-2.jpg', 'Jembatan Suramadu dari kejauhan sebelum aku belok selatan. Pamit dulu sama laut.', 1, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (3, 2, '/uploads/seed/mojo-1.jpg', 'Warung pecel Bu Sari. Nasi pecel + tempe goreng = Rp 8.000. Surga harga.', 0, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (4, 2, '/uploads/seed/mojo-2.jpg', 'Candi Trowulan keliatan dari jalan raya. Sejarah terhampar di pinggir aspal.', 1, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (5, 2, '/uploads/seed/mojo-3.jpg', 'Motor diparkir di bawah pohon rindang. Bensin full, semangat juga full.', 2, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (6, 3, '/uploads/seed/malang-1.jpg', 'Masuk Malang lewat jalur belakang. Kabut turun, suhu turun 10 derajat langsung.', 0, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (7, 3, '/uploads/seed/malang-2.jpg', 'Kafe kecil di jalan Ijen. Kopi susu Malang beda—ada manis-manis tersendiri.', 1, '2026-04-12 11:51:48');
INSERT INTO photos (id, checkpoint_id, photo_url, caption, "order", created_at) VALUES (8, 3, '/uploads/seed/malang-3.jpg', 'View Gunung Semeru dari ketinggian. Ini yang bikin capek perjalanan terbayar lunas.', 2, '2026-04-12 11:51:48');
